apiVersion: apps/v1
kind: Deployment
metadata:
  name: child-growth-api-dev-deployment
  namespace: child-growth-api-dev
  labels: 
    app: child-growth-api-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: child-growth-api-dev
  template:
    metadata:
      labels: 
        app: child-growth-api-dev
    spec:
      containers:
        - name: child-growth-api
          image: ghcr.io/childgrowthbg/childgrowth-fastapi:main
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_USER
              value: testuser
            - name: DB_PASSWORD
              value: testpassword
            - name: DB_HOST
              value: "192.168.68.122"
            - name: DB_NAME
              value: child_growth_dev
            - name: DB_PORT
              value: "5432"
            - name: JWT_KEY
              value: 